// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Int = require("bs-platform/lib/js/belt_Int.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

var __x = Fs.readFileSync("./test.txt", "utf8").split("\n");

var __x$1 = __x.filter(function (line) {
      return line !== "";
    });

console.log(Belt_Array.reduce(__x$1.map(function (x) {
              return Belt_Option.getWithDefault(Belt_Int.fromString(x), 0);
            }), 0, (function (x, y) {
            return x + y | 0;
          })));

console.log(/* Blue */1);

var x = [
  1,
  2
];

var x$1 = x.join(",");

var x$2 = ",".split(x$1);

var goodResult = {
  TAG: /* Success */0,
  _0: "OK!"
};

var failedResult = {
  TAG: /* Failure */1,
  _0: ":(",
  _1: 400
};

var result = Math.random() > 0.5 ? goodResult : failedResult;

if (result.TAG) {
  console.log("Something's wrong. The error code is: " + result._1.toString());
} else {
  console.log("Success! " + result._0);
}

var color = /* Blue */1;

exports.color = color;
exports.x = x$2;
exports.goodResult = goodResult;
exports.failedResult = failedResult;
exports.result = result;
/*  Not a pure module */
