// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

function opWithFn(x, y, fn) {
  return 10 + Curry._2(fn, x, y) | 0;
}

console.log(opWithFn(2, 5, (function (a, b) {
            return a + b | 0;
          })));

console.log(Belt_Array.map([
          1,
          2,
          3
        ], (function (x) {
            return Math.imul(x, x);
          })));

exports.opWithFn = opWithFn;
/*  Not a pure module */
