// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Int = require("bs-platform/lib/js/belt_Int.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

function readIntsInputData(fileName) {
  var __x = Fs.readFileSync(fileName, "utf8").split("\n");
  var __x$1 = __x.filter(function (line) {
        return line !== "";
      });
  return __x$1.map(function (x) {
              return Belt_Option.getWithDefault(Belt_Int.fromString(x), 0);
            });
}

function readLinesInputData(fileName) {
  var __x = Fs.readFileSync(fileName, "utf8").split("\n");
  return __x.filter(function (line) {
              return line !== "";
            });
}

exports.readIntsInputData = readIntsInputData;
exports.readLinesInputData = readLinesInputData;
/* fs Not a pure module */
