// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Tools = require("../Utils/Tools.bs.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");
var Caml_string = require("bs-platform/lib/js/caml_string.js");

function parseData(lines) {
  return $$Array.map((function (line) {
                return $$Array.map((function (x) {
                              return Caml_string.get(x, 0);
                            }), line.split(""));
              }), lines);
}

function calculate(grid) {
  var height = grid.length;
  var width = Caml_array.get(grid, 0).length;
  var seq = Belt_Array.makeBy(height, (function (i) {
          return i;
        }));
  return Belt_Array.reduce(seq, 0, (function (acc, j) {
                var iT = Math.imul(j, 3);
                var i = Caml_int32.mod_(iT, width);
                if (Caml_array.get(Caml_array.get(grid, j), i) === /* "#" */35) {
                  return acc + 1 | 0;
                } else {
                  return acc;
                }
              }));
}

console.log("Day 03, Part 01:");

console.log(calculate(parseData(Tools.readLinesInputData("./input/aoc2020/day03.txt"))));

exports.parseData = parseData;
exports.calculate = calculate;
/*  Not a pure module */
